# Generated by Django 4.2 on 2023-04-04 13:21

import core.validators
from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230331_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoragePoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(verbose_name='Описание')),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, db_index=True, null=True, srid=4326, verbose_name='Где находится на карте')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('opening_hours', models.TimeField(blank=True, null=True, verbose_name='Время открытия')),
                ('closing_hours', models.TimeField(blank=True, null=True, verbose_name='Время закрытия')),
                ('phone', models.DecimalField(blank=True, decimal_places=0, help_text='В формате 71111111111', max_digits=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка на сайт')),
                ('address', models.TextField(null=True, validators=[core.validators.address_validate], verbose_name='Адрес')),
                ('address_for_cleaning', models.TextField(db_index=True, editable=False, null=True)),
                ('address_clean', models.TextField(db_index=True, editable=False, null=True, verbose_name='Стандартизированный адрес')),
                ('dadata_updated_at', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('dadata_info', models.JSONField(editable=False, null=True)),
                ('dadata_log', models.TextField(editable=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='storagepoi',
            constraint=models.UniqueConstraint(fields=('name', 'user'), name='uniq_name_user_is_active'),
        ),
    ]
