# Generated by Django 4.2 on 2023-04-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_order_uniq_user_storage_poi_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('debit', 'Дебетовая карта'), ('sbp', 'СБП'), ('qiwi', 'QIWI')], default='debit', max_length=100),
        ),
    ]
