# Generated by Django 4.2 on 2023-04-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_is_payed_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='form_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
