# Generated by Django 4.2 on 2023-04-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_order_form_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='form_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
