# Generated by Django 4.2 on 2023-04-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_order_form_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='form_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
