# Generated by Django 4.2 on 2023-04-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_order_form_url'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='uniq_user_storage_poi_is_active',
        ),
        migrations.AddField(
            model_name='storagepoi',
            name='available_bags',
            field=models.IntegerField(default=10, verbose_name='Количество доступных мешков'),
        ),
    ]
