# Generated by Django 4.2 on 2023-04-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_order_form_url_order_pin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pin_code',
            field=models.CharField(db_index=True, default='745168', editable=False, max_length=6),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('pin_code', 'storage_poi'), name='uniq_pin_code_storage_poi'),
        ),
    ]
