# Generated by Django 4.2 on 2023-04-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_order_pin_code_order_uniq_pin_code_storage_poi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='pin_code',
            field=models.CharField(db_index=True, default='150131', editable=False, max_length=6),
        ),
    ]
