# Generated by Django 4.2 on 2023-04-19 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_order_uniq_pin_code_storage_poi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pin_code',
            field=models.CharField(db_index=True, default='785667', editable=False, max_length=6),
        ),
        migrations.AlterField(
            model_name='storagepoi',
            name='available_bags',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество доступных мешков'),
        ),
    ]
