# Generated by Django 4.2 on 2023-04-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_order_pin_code_alter_storagepoi_available_bags'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_payed_for_extra_days',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='pin_code',
            field=models.CharField(db_index=True, default='662825', editable=False, max_length=6),
        ),
    ]
